name: MY FIRST GITHUB ACTION

on:
  push:
    branches:
      - master
        main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Github Actions
        run: echo "HELLO world to GITHUB ACTIONS"

